// File generated by FlutterFire CLI.
// This file should be version controlled.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLA4FZTGNRnmpTYpgxLLCxkpniHj3xUcs',
    appId: '1:683153003601:android:00f712ed1650cc4afcd470',
    messagingSenderId: '683153003601',
    projectId: 'cazlync-app-final',
    storageBucket: 'cazlync-app-final.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDs6Dp-V1-RHOhlOvVDo0rxi3sLaeqbho',
    appId: '1:683153003601:ios:9ac6173b077751abfcd470',
    messagingSenderId: '683153003601',
    projectId: 'cazlync-app-final',
    storageBucket: 'cazlync-app-final.firebasestorage.app',
    iosBundleId: 'com.cazlync.cazlync',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCxfswSfO6qWIeCLzo6oNRYcf1mrZ46r8',
    appId: '1:683153003601:web:0dba5e53f52f33a0fcd470',
    messagingSenderId: '683153003601',
    projectId: 'cazlync-app-final',
    authDomain: 'cazlync-app-final.firebaseapp.com',
    storageBucket: 'cazlync-app-final.firebasestorage.app',
    measurementId: 'G-L2WC45MX4C',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDs6Dp-V1-RHOhlOvVDo0rxi3sLaeqbho',
    appId: '1:683153003601:ios:9ac6173b077751abfcd470',
    messagingSenderId: '683153003601',
    projectId: 'cazlync-app-final',
    storageBucket: 'cazlync-app-final.firebasestorage.app',
    iosBundleId: 'com.cazlync.cazlync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCxfswSfO6qWIeCLzo6oNRYcf1mrZ46r8',
    appId: '1:683153003601:web:f62689646e51757dfcd470',
    messagingSenderId: '683153003601',
    projectId: 'cazlync-app-final',
    authDomain: 'cazlync-app-final.firebaseapp.com',
    storageBucket: 'cazlync-app-final.firebasestorage.app',
    measurementId: 'G-KQWX6G4EE2',
  );

}